// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: bills.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createBill = `-- name: CreateBill :one
INSERT INTO bills (user_id, customer_id, customer_name, amount, amount_paid)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, customer_name, amount, created_at, customer_id, amount_paid
`

type CreateBillParams struct {
	UserID       uuid.UUID
	CustomerID   uuid.NullUUID
	CustomerName string
	Amount       string
	AmountPaid   string
}

// Insert the bill header, scoped to the shop. RETURNING hands back the
// server-generated id — the repository NEEDS it to insert the bill_items
// against it, all inside ONE transaction (same pattern as CreateItem).
// customer_id is NULL for walk-in; customer_name is the denormalized snapshot.
// amount = bill TOTAL (dashboard sums this column — name is load-bearing).
// NOTE: customer_id/amount_paid trail created_at in the column list because
// migration 005 ALTER-appended them — keeping DDL order lets sqlc reuse the
// Bill model instead of emitting per-query Row structs.
func (q *Queries) CreateBill(ctx context.Context, arg CreateBillParams) (Bill, error) {
	row := q.db.QueryRowContext(ctx, createBill,
		arg.UserID,
		arg.CustomerID,
		arg.CustomerName,
		arg.Amount,
		arg.AmountPaid,
	)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CustomerName,
		&i.Amount,
		&i.CreatedAt,
		&i.CustomerID,
		&i.AmountPaid,
	)
	return i, err
}

const createBillItem = `-- name: CreateBillItem :one
INSERT INTO bill_items (bill_id, item_id, variant_id, name, quantity, unit_price, line_total)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, bill_id, item_id, variant_id, name, quantity, unit_price, line_total, created_at
`

type CreateBillItemParams struct {
	BillID    uuid.UUID
	ItemID    uuid.NullUUID
	VariantID uuid.NullUUID
	Name      string
	Quantity  string
	UnitPrice string
	LineTotal string
}

// Insert one line against an existing bill. Called N times by the repo inside
// the settlement transaction. Stores the RESOLVED result (name + price + qty +
// total) — item_id/variant_id are provenance pointers only, nullable by design
// (NULL item_id = miscellaneous; NULL variant_id = Type B or miscellaneous).
func (q *Queries) CreateBillItem(ctx context.Context, arg CreateBillItemParams) (BillItem, error) {
	row := q.db.QueryRowContext(ctx, createBillItem,
		arg.BillID,
		arg.ItemID,
		arg.VariantID,
		arg.Name,
		arg.Quantity,
		arg.UnitPrice,
		arg.LineTotal,
	)
	var i BillItem
	err := row.Scan(
		&i.ID,
		&i.BillID,
		&i.ItemID,
		&i.VariantID,
		&i.Name,
		&i.Quantity,
		&i.UnitPrice,
		&i.LineTotal,
		&i.CreatedAt,
	)
	return i, err
}

const getBillByID = `-- name: GetBillByID :one
SELECT id, user_id, customer_name, amount, created_at, customer_id, amount_paid
FROM bills
WHERE id = $1 AND user_id = $2
`

type GetBillByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Single bill, scoped by BOTH id AND user_id — a shop can never read another
// shop's bill even with a guessed id (same cross-shop guard as customers).
func (q *Queries) GetBillByID(ctx context.Context, arg GetBillByIDParams) (Bill, error) {
	row := q.db.QueryRowContext(ctx, getBillByID, arg.ID, arg.UserID)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CustomerName,
		&i.Amount,
		&i.CreatedAt,
		&i.CustomerID,
		&i.AmountPaid,
	)
	return i, err
}

const getBillItems = `-- name: GetBillItems :many
SELECT id, bill_id, item_id, variant_id, name, quantity, unit_price, line_total, created_at
FROM bill_items
WHERE bill_id = $1
ORDER BY created_at, id
`

// Lines for one bill. NOTE: bill_items carry no user_id — tenancy is enforced
// one level up by GetBillByID (transitive tenancy, same as item_variants).
// created_at is NOW() = transaction start, so every line in a bill shares one
// timestamp; the id tiebreak just makes the order deterministic.
func (q *Queries) GetBillItems(ctx context.Context, billID uuid.UUID) ([]BillItem, error) {
	rows, err := q.db.QueryContext(ctx, getBillItems, billID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BillItem
	for rows.Next() {
		var i BillItem
		if err := rows.Scan(
			&i.ID,
			&i.BillID,
			&i.ItemID,
			&i.VariantID,
			&i.Name,
			&i.Quantity,
			&i.UnitPrice,
			&i.LineTotal,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBills = `-- name: ListBills :many
SELECT id, user_id, customer_name, amount, created_at, customer_id, amount_paid
FROM bills
WHERE user_id = $1
ORDER BY created_at DESC
`

// Full bill list for one shop, newest first. Backed by idx_bills_user_created_at
// (same index the dashboard's recent-bills query uses). Headers only — line
// items are fetched per-bill via GetBillItems on the detail view.
func (q *Queries) ListBills(ctx context.Context, userID uuid.UUID) ([]Bill, error) {
	rows, err := q.db.QueryContext(ctx, listBills, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bill
	for rows.Next() {
		var i Bill
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CustomerName,
			&i.Amount,
			&i.CreatedAt,
			&i.CustomerID,
			&i.AmountPaid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
