// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: customers.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (user_id, name, phone, email, notes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, phone, email, notes, false AS has_dues, created_at, updated_at
`

type CreateCustomerParams struct {
	UserID uuid.UUID
	Name   string
	Phone  string
	Email  sql.NullString
	Notes  sql.NullString
}

type CreateCustomerRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	Phone     string
	Email     sql.NullString
	Notes     sql.NullString
	HasDues   bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

// Insert a new customer scoped to the owning shop (user_id).
// RETURNING hands back the full row so the handler can echo it to the client
// with no second query. has_dues is always false for a brand-new customer
// (no khata_entries exist yet) — emitted as a literal so the Go contract
// (HasDues bool) is preserved after migration 006 dropped the column.
func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (CreateCustomerRow, error) {
	row := q.db.QueryRowContext(ctx, createCustomer,
		arg.UserID,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Notes,
	)
	var i CreateCustomerRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Notes,
		&i.HasDues,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCustomer = `-- name: DeleteCustomer :exec
DELETE FROM customers
WHERE id = $1 AND user_id = $2
`

type DeleteCustomerParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Hard delete, scoped by id AND user_id. The dues-check happens in the
// SERVICE layer before this runs (defense layer 2 returns 409). This query
// just deletes — it trusts the service already gated it.
func (q *Queries) DeleteCustomer(ctx context.Context, arg DeleteCustomerParams) error {
	_, err := q.db.ExecContext(ctx, deleteCustomer, arg.ID, arg.UserID)
	return err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT
    c.id,
    c.user_id,
    c.name,
    c.phone,
    c.email,
    c.notes,
    COALESCE(
        SUM(CASE WHEN k.type = 'credit' THEN k.amount ELSE -k.amount END),
        0
    )::numeric <> 0 AS has_dues,
    c.created_at,
    c.updated_at
FROM customers c
LEFT JOIN khata_entries k ON k.customer_id = c.id AND k.user_id = c.user_id
WHERE c.id = $1 AND c.user_id = $2
GROUP BY c.id, c.user_id, c.name, c.phone, c.email, c.notes, c.created_at, c.updated_at
`

type GetCustomerByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetCustomerByIDRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	Phone     string
	Email     sql.NullString
	Notes     sql.NullString
	HasDues   bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

// Single customer, scoped by BOTH id AND user_id — a shop can never read
// another shop's customer even with a guessed id.
// has_dues computed the same way as ListCustomers.
func (q *Queries) GetCustomerByID(ctx context.Context, arg GetCustomerByIDParams) (GetCustomerByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByID, arg.ID, arg.UserID)
	var i GetCustomerByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Notes,
		&i.HasDues,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT
    c.id,
    c.user_id,
    c.name,
    c.phone,
    c.email,
    c.notes,
    COALESCE(
        SUM(CASE WHEN k.type = 'credit' THEN k.amount ELSE -k.amount END),
        0
    )::numeric <> 0 AS has_dues,
    c.created_at,
    c.updated_at
FROM customers c
LEFT JOIN khata_entries k ON k.customer_id = c.id AND k.user_id = c.user_id
WHERE c.user_id = $1
GROUP BY c.id, c.user_id, c.name, c.phone, c.email, c.notes, c.created_at, c.updated_at
ORDER BY c.name
`

type ListCustomersRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	Phone     string
	Email     sql.NullString
	Notes     sql.NullString
	HasDues   bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

// Full list for one shop, alphabetical. Backed by idx_customers_user_name.
// has_dues is computed: balance (SUM credits − SUM payments) != 0.
// LEFT JOIN so customers with no entries are included (has_dues = false).
func (q *Queries) ListCustomers(ctx context.Context, userID uuid.UUID) ([]ListCustomersRow, error) {
	rows, err := q.db.QueryContext(ctx, listCustomers, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomersRow
	for rows.Next() {
		var i ListCustomersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.Notes,
			&i.HasDues,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customers
SET name = $3, phone = $4, email = $5, notes = $6, updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, phone, email, notes, false AS has_dues, created_at, updated_at
`

type UpdateCustomerParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	Name   string
	Phone  string
	Email  sql.NullString
	Notes  sql.NullString
}

type UpdateCustomerRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	Phone     string
	Email     sql.NullString
	Notes     sql.NullString
	HasDues   bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

// Update identity fields, bump updated_at. Scoped by id AND user_id.
// has_dues emitted as false (identity updates never change balances; the UI
// refreshes the list after update, which calls ListCustomers with the real value).
func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (UpdateCustomerRow, error) {
	row := q.db.QueryRowContext(ctx, updateCustomer,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Notes,
	)
	var i UpdateCustomerRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Notes,
		&i.HasDues,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
