// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: customers.sql

package sqlcgen

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (user_id, name, phone, email, notes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, phone, email, notes, has_dues, created_at, updated_at
`

type CreateCustomerParams struct {
	UserID uuid.UUID
	Name   string
	Phone  string
	Email  sql.NullString
	Notes  sql.NullString
}

// Insert a new customer scoped to the owning shop (user_id).
// RETURNING hands back the full row (server-generated id, has_dues default,
// timestamps) so the handler can echo it to the client with no second query.
func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRowContext(ctx, createCustomer,
		arg.UserID,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Notes,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Notes,
		&i.HasDues,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCustomer = `-- name: DeleteCustomer :exec
DELETE FROM customers
WHERE id = $1 AND user_id = $2
`

type DeleteCustomerParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Hard delete, scoped by id AND user_id. The dues-check happens in the
// SERVICE layer before this runs (defense layer 2 returns 409). This query
// just deletes — it trusts the service already gated it.
func (q *Queries) DeleteCustomer(ctx context.Context, arg DeleteCustomerParams) error {
	_, err := q.db.ExecContext(ctx, deleteCustomer, arg.ID, arg.UserID)
	return err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, user_id, name, phone, email, notes, has_dues, created_at, updated_at
FROM customers
WHERE id = $1 AND user_id = $2
`

type GetCustomerByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Single customer, scoped by BOTH id AND user_id — a shop can never read
// another shop's customer even with a guessed id.
func (q *Queries) GetCustomerByID(ctx context.Context, arg GetCustomerByIDParams) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByID, arg.ID, arg.UserID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Notes,
		&i.HasDues,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, user_id, name, phone, email, notes, has_dues, created_at, updated_at
FROM customers
WHERE user_id = $1
ORDER BY name
`

// Full list for one shop, alphabetical. Backed by idx_customers_user_name.
func (q *Queries) ListCustomers(ctx context.Context, userID uuid.UUID) ([]Customer, error) {
	rows, err := q.db.QueryContext(ctx, listCustomers, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.Notes,
			&i.HasDues,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customers
SET name = $3, phone = $4, email = $5, notes = $6, updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, phone, email, notes, has_dues, created_at, updated_at
`

type UpdateCustomerParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	Name   string
	Phone  string
	Email  sql.NullString
	Notes  sql.NullString
}

// Update identity fields, bump updated_at. Scoped by id AND user_id.
// has_dues is NOT updatable here — it's khata-owned (temporary manual flip for now).
func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error) {
	row := q.db.QueryRowContext(ctx, updateCustomer,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Notes,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Notes,
		&i.HasDues,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
