// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: dashboard.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getRecentBills = `-- name: GetRecentBills :many
SELECT id, customer_name, amount, created_at FROM bills
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 3
`

type GetRecentBillsRow struct {
	ID           uuid.UUID
	CustomerName string
	Amount       string
	CreatedAt    time.Time
}

func (q *Queries) GetRecentBills(ctx context.Context, userID uuid.UUID) ([]GetRecentBillsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentBills, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentBillsRow
	for rows.Next() {
		var i GetRecentBillsRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerName,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodaySales = `-- name: GetTodaySales :one
SELECT COALESCE(SUM(amount), 0)::numeric AS total_sales FROM bills
WHERE user_id = $1
AND DATE(created_at AT TIME ZONE 'Asia/Kolkata') = CURRENT_DATE AT TIME ZONE 'Asia/Kolkata'
`

func (q *Queries) GetTodaySales(ctx context.Context, userID uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getTodaySales, userID)
	var total_sales string
	err := row.Scan(&total_sales)
	return total_sales, err
}
