// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: inventory.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (user_id, name, pricing_type, rate, unit)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, pricing_type, rate, unit, created_at, updated_at
`

type CreateItemParams struct {
	UserID      uuid.UUID
	Name        string
	PricingType string
	Rate        sql.NullString
	Unit        sql.NullString
}

// Insert the parent item row, scoped to the shop. RETURNING hands back the
// server-generated id — the repository NEEDS this id to then insert the
// variant rows against it, all inside ONE transaction.
func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, createItem,
		arg.UserID,
		arg.Name,
		arg.PricingType,
		arg.Rate,
		arg.Unit,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.PricingType,
		&i.Rate,
		&i.Unit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVariant = `-- name: CreateVariant :one
INSERT INTO item_variants (item_id, label, price, is_default, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, item_id, label, price, is_default, description, created_at, updated_at
`

type CreateVariantParams struct {
	ItemID      uuid.UUID
	Label       string
	Price       string
	IsDefault   bool
	Description sql.NullString
}

// Insert one variant against an existing item. Called N times by the repo
// (once per variant) inside the create transaction, and standalone by the
// add-variant endpoint. The repo passes item_id from the just-created item.
func (q *Queries) CreateVariant(ctx context.Context, arg CreateVariantParams) (ItemVariant, error) {
	row := q.db.QueryRowContext(ctx, createVariant,
		arg.ItemID,
		arg.Label,
		arg.Price,
		arg.IsDefault,
		arg.Description,
	)
	var i ItemVariant
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Label,
		&i.Price,
		&i.IsDefault,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteItem = `-- name: DeleteItem :exec
DELETE FROM items
WHERE id = $1 AND user_id = $2
`

type DeleteItemParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Hard delete, scoped by id AND user_id. ON DELETE CASCADE drops the item's
// variants automatically — no separate variant delete needed here.
func (q *Queries) DeleteItem(ctx context.Context, arg DeleteItemParams) error {
	_, err := q.db.ExecContext(ctx, deleteItem, arg.ID, arg.UserID)
	return err
}

const deleteVariant = `-- name: DeleteVariant :exec
DELETE FROM item_variants
WHERE id = $1
`

func (q *Queries) DeleteVariant(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteVariant, id)
	return err
}

const getItemByID = `-- name: GetItemByID :one
SELECT id, user_id, name, pricing_type, rate, unit, created_at, updated_at
FROM items
WHERE id = $1 AND user_id = $2
`

type GetItemByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Single item, scoped by id AND user_id (same cross-shop guard as customers).
// Used by the variant guard: service reads pricing_type before allowing a
// variant insert — a 'loose' item must reject variants.
func (q *Queries) GetItemByID(ctx context.Context, arg GetItemByIDParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItemByID, arg.ID, arg.UserID)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.PricingType,
		&i.Rate,
		&i.Unit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVariantByID = `-- name: GetVariantByID :one
SELECT id, item_id, label, price, is_default, description, created_at, updated_at
FROM item_variants
WHERE id = $1
`

// Single variant by its own id. Used for the 404 check before update/delete.
// NOTE: variants have no user_id column — tenancy is enforced one level up,
// by first confirming the parent item belongs to this user (GetItemByID).
func (q *Queries) GetVariantByID(ctx context.Context, id uuid.UUID) (ItemVariant, error) {
	row := q.db.QueryRowContext(ctx, getVariantByID, id)
	var i ItemVariant
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Label,
		&i.Price,
		&i.IsDefault,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listItemsWithVariants = `-- name: ListItemsWithVariants :many
SELECT
    i.id           AS item_id,
    i.name         AS item_name,
    i.pricing_type,
    i.rate,
    i.unit,
    i.created_at   AS item_created_at,
    i.updated_at   AS item_updated_at,
    v.id           AS variant_id,
    v.label,
    v.price,
    v.is_default,
    v.description,
    v.created_at   AS variant_created_at,
    v.updated_at   AS variant_updated_at
FROM items i
LEFT JOIN item_variants v ON i.id = v.item_id
WHERE i.user_id = $1
ORDER BY i.name
`

type ListItemsWithVariantsRow struct {
	ItemID           uuid.UUID
	ItemName         string
	PricingType      string
	Rate             sql.NullString
	Unit             sql.NullString
	ItemCreatedAt    time.Time
	ItemUpdatedAt    time.Time
	VariantID        uuid.NullUUID
	Label            sql.NullString
	Price            sql.NullString
	IsDefault        sql.NullBool
	Description      sql.NullString
	VariantCreatedAt sql.NullTime
	VariantUpdatedAt sql.NullTime
}

// LEFT JOIN so Type B (loose) items with zero variants still appear.
// Returns FLAT rows: a unit item with 3 variants = 3 rows (item cols repeated,
// one variant per row); a loose item = 1 row with all variant cols NULL.
// The repository groups these flat rows into nested objects in Go, keyed by
// item_id, preserving this ORDER BY name via a parallel ordered slice.
func (q *Queries) ListItemsWithVariants(ctx context.Context, userID uuid.UUID) ([]ListItemsWithVariantsRow, error) {
	rows, err := q.db.QueryContext(ctx, listItemsWithVariants, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemsWithVariantsRow
	for rows.Next() {
		var i ListItemsWithVariantsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.ItemName,
			&i.PricingType,
			&i.Rate,
			&i.Unit,
			&i.ItemCreatedAt,
			&i.ItemUpdatedAt,
			&i.VariantID,
			&i.Label,
			&i.Price,
			&i.IsDefault,
			&i.Description,
			&i.VariantCreatedAt,
			&i.VariantUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItem = `-- name: UpdateItem :one
UPDATE items
SET name = $3, rate = $4, unit = $5, updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, pricing_type, rate, unit, created_at, updated_at
`

type UpdateItemParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	Name   string
	Rate   sql.NullString
	Unit   sql.NullString
}

// Update item fields, bump updated_at. Scoped by id AND user_id.
func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, updateItem,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Rate,
		arg.Unit,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.PricingType,
		&i.Rate,
		&i.Unit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVariant = `-- name: UpdateVariant :one
UPDATE item_variants
SET label = $2, price = $3, is_default = $4, description = $5, updated_at = NOW()
WHERE id = $1
RETURNING id, item_id, label, price, is_default, description, created_at, updated_at
`

type UpdateVariantParams struct {
	ID          uuid.UUID
	Label       string
	Price       string
	IsDefault   bool
	Description sql.NullString
}

func (q *Queries) UpdateVariant(ctx context.Context, arg UpdateVariantParams) (ItemVariant, error) {
	row := q.db.QueryRowContext(ctx, updateVariant,
		arg.ID,
		arg.Label,
		arg.Price,
		arg.IsDefault,
		arg.Description,
	)
	var i ItemVariant
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Label,
		&i.Price,
		&i.IsDefault,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
