// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: khata.sql

package sqlcgen

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getCustomerBalance = `-- name: GetCustomerBalance :one
SELECT COALESCE(
    SUM(CASE WHEN type = 'credit' THEN amount ELSE -amount END),
    0
)::numeric AS balance
FROM khata_entries
WHERE user_id = $1 AND customer_id = $2
`

type GetCustomerBalanceParams struct {
	UserID     uuid.UUID
	CustomerID uuid.UUID
}

// Derived balance: SUM(credits) − SUM(payments).
// Returns 0 when the customer has no entries (COALESCE).
// ::numeric cast ensures sqlc emits string (same convention as money columns
// throughout the codebase), not interface{}.
func (q *Queries) GetCustomerBalance(ctx context.Context, arg GetCustomerBalanceParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getCustomerBalance, arg.UserID, arg.CustomerID)
	var balance string
	err := row.Scan(&balance)
	return balance, err
}

const insertKhataEntry = `-- name: InsertKhataEntry :one
INSERT INTO khata_entries (user_id, customer_id, type, amount, bill_id, note)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, customer_id, type, amount, bill_id, note, created_at
`

type InsertKhataEntryParams struct {
	UserID     uuid.UUID
	CustomerID uuid.UUID
	Type       string
	Amount     string
	BillID     uuid.NullUUID
	Note       sql.NullString
}

// Insert one khata entry ('credit' or 'payment') for a customer.
// Called in two places:
//   1. Inside the billing settlement transaction (credit + optional payment
//      written by billing_repository.CreateBillWithItems via the shared tx).
//   2. Directly by the "Record Payment" endpoint (payment only).
// bill_id is set only for 'credit' entries; NULL for standalone 'payment'.
func (q *Queries) InsertKhataEntry(ctx context.Context, arg InsertKhataEntryParams) (KhataEntry, error) {
	row := q.db.QueryRowContext(ctx, insertKhataEntry,
		arg.UserID,
		arg.CustomerID,
		arg.Type,
		arg.Amount,
		arg.BillID,
		arg.Note,
	)
	var i KhataEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CustomerID,
		&i.Type,
		&i.Amount,
		&i.BillID,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const listKhataEntries = `-- name: ListKhataEntries :many
SELECT id, user_id, customer_id, type, amount, bill_id, note, created_at
FROM khata_entries
WHERE user_id = $1 AND customer_id = $2
ORDER BY created_at, id
`

type ListKhataEntriesParams struct {
	UserID     uuid.UUID
	CustomerID uuid.UUID
}

// Chronological ledger for one customer of one shop (timeline view).
// Oldest first — credits and payments within the same settlement transaction
// share the tx timestamp; id breaks ties deterministically.
func (q *Queries) ListKhataEntries(ctx context.Context, arg ListKhataEntriesParams) ([]KhataEntry, error) {
	rows, err := q.db.QueryContext(ctx, listKhataEntries, arg.UserID, arg.CustomerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KhataEntry
	for rows.Next() {
		var i KhataEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CustomerID,
			&i.Type,
			&i.Amount,
			&i.BillID,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
