// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: me.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, shop_name, phone, email FROM users WHERE id = $1
`

type GetUserByIDRow struct {
	ID       uuid.UUID
	Name     string
	ShopName string
	Phone    string
	Email    string
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShopName,
		&i.Phone,
		&i.Email,
	)
	return i, err
}
