// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcgen

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Bill struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	CustomerName string
	Amount       string
	CreatedAt    time.Time
}

type Customer struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	Phone     string
	Email     sql.NullString
	Notes     sql.NullString
	HasDues   bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Item struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	PricingType string
	Rate        sql.NullString
	Unit        sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ItemVariant struct {
	ID          uuid.UUID
	ItemID      uuid.UUID
	Label       string
	Price       string
	IsDefault   bool
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID        uuid.UUID
	Name      string
	ShopName  string
	Phone     string
	Email     string
	Password  string
	CreatedAt time.Time
}
