name: local
variables:
  - name: baseUrl
    value: http://localhost:8080
  - name: authToken
    value: ""
  - name: customerId
    value: 4dec0ff0-3a26-4e84-ab6d-ec0bb89decd8
  - name: billId
    value: ""
