import 'package:equatable/equatable.dart';

import '../../../inventory/domain/entities/item.dart';
import '../bill_math.dart' as bm;

/// Where a fresh [UnitItem] card lands: its default variant, else the
/// first.
///
/// Deliberately a for-loop. `firstWhere(test, orElse: () => …)` is a
/// RUNTIME TypeError when the list is actually `List<ItemVariantModel>`
/// (which everything parsed by the frozen `itemFromJson` is): Dart's
/// covariant generics reject an `() => ItemVariant` closure for the
/// runtime list's `(() => ItemVariantModel)?` orElse slot. Loops carry no
/// closure types, so they're immune. Keep ALL variant lookups in this
/// shape.
ItemVariant defaultVariantOf(UnitItem item) {
  for (final v in item.variants) {
    if (v.isDefault) return v;
  }
  return item.variants.first;
}

/// A line on the DRAFT bill — the shopkeeper's editable notebook (§9–§10).
///
/// Not the persisted [BillItem]: a draft line keeps enough provenance to
/// stay interactive (swipe variants, live measure recompute) and only
/// resolves to the flat `{item_id?, variant_id?, name, quantity, unit_price}`
/// shape when submitted via `POST /v1/bills`.
///
/// [id] is a LOCAL draft identity (generated by the bloc) used to address
/// edits/removals in the list — never sent to the server.
sealed class DraftLine extends Equatable {
  const DraftLine({required this.id});

  final String id;

  /// Resolved fields — what the server will snapshot.
  String get name;
  double get quantity;
  double get unitPrice;
  double get lineTotal => bm.lineTotal(quantity, unitPrice);

  /// Provenance pointers for the request body (null per the origin table).
  String? get itemId;
  String? get variantId;
}

/// Type A — unit item with swipeable variants (§10).
/// Swipe = pick variant = pick price. A hand-typed [priceOverride] wins
/// until the next swipe clears it (notebook semantics: the last scribble
/// counts).
class UnitDraftLine extends DraftLine {
  const UnitDraftLine({
    required super.id,
    required this.item,
    required this.selectedVariantId,
    this.count = 1,
    this.nameOverride,
    this.priceOverride,
  });

  final UnitItem item;
  final String selectedVariantId;
  final double count;
  final String? nameOverride;
  final double? priceOverride;

  /// Plain loop, NOT `firstWhere(orElse:)`: the frozen inventory model
  /// builds variants via `.map(ItemVariantModel.fromJson).toList()`, so at
  /// runtime the list is `List<ItemVariantModel>` and an
  /// `orElse: () => ItemVariant` closure is a TypeError (covariance).
  ItemVariant get selectedVariant {
    for (final v in item.variants) {
      if (v.id == selectedVariantId) return v;
    }
    return item.variants.first;
  }

  @override
  String get name => nameOverride ?? item.name;

  @override
  double get quantity => count;

  @override
  double get unitPrice => priceOverride ?? selectedVariant.price;

  @override
  String? get itemId => item.id;

  @override
  String? get variantId => selectedVariantId;

  /// Swipe semantics (§10): selecting a variant CLEARS a hand-typed price —
  /// the swiped variant's price is now the line's price.
  UnitDraftLine swipeTo(String variantId) => UnitDraftLine(
        id: id,
        item: item,
        selectedVariantId: variantId,
        count: count,
        nameOverride: nameOverride,
        priceOverride: null,
      );

  /// Cell edits. Never clears overrides — only [swipeTo] resets the price.
  UnitDraftLine copyWith({
    double? count,
    String? nameOverride,
    double? priceOverride,
  }) =>
      UnitDraftLine(
        id: id,
        item: item,
        selectedVariantId: selectedVariantId,
        count: count ?? this.count,
        nameOverride: nameOverride ?? this.nameOverride,
        priceOverride: priceOverride ?? this.priceOverride,
      );

  @override
  List<Object?> get props =>
      [id, item, selectedVariantId, count, nameOverride, priceOverride];
}

/// Type B — loose/weight-priced item (§10). The shopkeeper types the
/// measure (0.750 kg) and the line cost recomputes LIVE: `rate × measure`.
/// Manual on-ramp only — no label, no scan.
class LooseDraftLine extends DraftLine {
  const LooseDraftLine({
    required super.id,
    required this.item,
    this.measure = 0,
    this.nameOverride,
    this.rateOverride,
  });

  final LooseItem item;

  /// Measure in the item's [LooseItem.unit] (e.g. 0.750 for 750 g @ ₹/kg).
  final double measure;
  final String? nameOverride;
  final double? rateOverride;

  @override
  String get name => nameOverride ?? item.name;

  @override
  double get quantity => measure;

  @override
  double get unitPrice => rateOverride ?? item.rate;

  @override
  String? get itemId => item.id;

  @override
  String? get variantId => null;

  LooseDraftLine copyWith({
    double? measure,
    String? nameOverride,
    double? rateOverride,
  }) =>
      LooseDraftLine(
        id: id,
        item: item,
        measure: measure ?? this.measure,
        nameOverride: nameOverride ?? this.nameOverride,
        rateOverride: rateOverride ?? this.rateOverride,
      );

  @override
  List<Object?> get props => [id, item, measure, nameOverride, rateOverride];
}

/// Miscellaneous — the escape hatch (§8). Free name + qty + price, no
/// inventory row. Scan's unmatched labels arrive as misc lines with
/// name + qty pre-filled and price 0, ready for the shopkeeper to type.
class MiscDraftLine extends DraftLine {
  const MiscDraftLine({
    required super.id,
    this.name = '',
    this.count = 1,
    this.price = 0,
  });

  @override
  final String name;
  final double count;
  final double price;

  @override
  double get quantity => count;

  @override
  double get unitPrice => price;

  @override
  String? get itemId => null;

  @override
  String? get variantId => null;

  MiscDraftLine copyWith({String? name, double? count, double? price}) =>
      MiscDraftLine(
        id: id,
        name: name ?? this.name,
        count: count ?? this.count,
        price: price ?? this.price,
      );

  @override
  List<Object?> get props => [id, name, count, price];
}
